[package]
name = "exam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-stable-structures = "0.5.4"
serde = "1.0.132"
ic-cdk-macros = "0.8.1"